### ISSUE TITLE
Getting started with Github Pages

### ISSUE THREAD

**Issue by snandit** [USoC2020/Forest_fire_prediction#11]
- Use your personal Github account to create a repository for this task, and enable the GITHUB PAGES option from settings.
- Now create a basic layout of a web page and add your introduction.
- Take a screenshot of the webpage and rename it with your Github username.
- Now, add this screenshot to the folder named "Screenshots" in the project repository- ** "Forest_fire_prediction"**
** Make sure that no other file containing your introduction, else than a screenshot should be added to the project repository. **

**Comment by 500075374** [comment]
8 PRs Merged. 
Closing the issue.
